version: "3"

services:
  go-api:
    restart: always
    tty: true
    container_name: test_debug_go_api
    build:
      context: .
      dockerfile: ./app/Dockerfile
      target: debug
    
    ports:
      - "5045:5045"
      # port debug
      - "2345:2345" 
    volumes:
      - ./app/src:/app/src
    
  